steps:
  - label: "CUDA Tests Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e 'println("--- :julia: Instantiating project")
                using Pkg
                Pkg.develop(; path=pwd())
                Pkg.develop(; name="CUDA")' || exit 3

      julia -e 'println("+++ :julia: Running tests")
                using Pkg
                Pkg.test("CUDA"; coverage=true, test_args=["base/kernelabstractions"])'

      julia -e 'println("+++ :julia: Running benchmarks")
                include("test/benchmarks.jl")'

      buildkite-agent artifact upload test/benchmark_results/*

    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 120
    soft_fail:
      - exit_status: 3

  - label: "Metal Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e 'println("--- :julia: Instantiating project")
                using Pkg
                Pkg.develop(; path=pwd())
                Pkg.develop(; name="Metal")' || exit 3

      julia -e 'println("+++ :julia: Running tests")
                using Pkg
                Pkg.test("Metal"; coverage=true, test_args=["kernelabstractions"])'
    agents:
      queue: "juliaecosystem"
      os: "macos"
      arch: "aarch64"
    timeout_in_minutes: 120
    soft_fail:
      - exit_status: 3

  - label: "oneAPI Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e 'println("--- :julia: Instantiating project")
                using Pkg
                Pkg.develop(; path=pwd())
                Pkg.develop(; name="oneAPI")' || exit 3

      julia -e 'println("+++ :julia: Running tests")
                using Pkg
                Pkg.test("oneAPI"; coverage=true, test_args=["kernelabstractions"])'
    agents:
      queue: "juliagpu"
      intel: "*"
    timeout_in_minutes: 120
    soft_fail:
      - exit_status: 3

  - label: "AMDGPU Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.10"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e 'println("--- :julia: Instantiating project")
                using Pkg
                Pkg.develop(; path=pwd())
                Pkg.develop(; name="AMDGPU")' || exit 3

      julia -e 'println("+++ :julia: Running tests")
                using Pkg
                Pkg.test("AMDGPU"; coverage=true, test_args=["kernelabstractions"])'
    agents:
      queue: "juliagpu"
      rocm: "*"
    timeout_in_minutes: 120
    soft_fail:
      - exit_status: 3
    env:
      JULIA_NUM_THREADS: 4