steps:
  - group: ":racehorse: Benchmarks"
    steps:
      - label: "CPU: Run Benchmarks with {{matrix.threads}} thread(s)"
        key: "cpu-benchmarks"
        matrix:
          setup:
            threads:
              - "1"
              - "2"
              - "4"
              - "8"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
          '
          julia --project=benchmarks --threads={{matrix.threads}} benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/CPUbenchmarks{{matrix.threads}}threads.json"
        agents:
          queue: "benchmark"
        env:
          BENCHMARK_GROUP: CPU
        timeout_in_minutes: 12

      - label: "CUDA: Run Benchmarks"
        key: "cuda-benchmarks"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
              Pkg.add("CUDA");
          '
          julia --project=benchmarks benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/CUDAbenchmarks.json"
        agents:
          queue: "juliagpu"
          cuda: "*"
        env:
          BENCHMARK_GROUP: CUDA
        timeout_in_minutes: 12

      - label: "AMDGPU: Run Benchmarks"
        key: "amdgpu-benchmarks"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
              Pkg.add("AMDGPU");
          '
          julia --project=benchmarks benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/AMDGPUbenchmarks.json"
        agents:
          queue: "juliagpu"
          rocm: "*"
        env:
          BENCHMARK_GROUP: AMDGPU
        timeout_in_minutes: 12

      - label: "oneAPI: Run Benchmarks"
        key: "oneapi-benchmarks"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
              Pkg.add("oneAPI");
          '
          julia --project=benchmarks benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/oneAPIbenchmarks.json"
        agents:
          queue: "juliagpu"
          intel: "*"
        env:
          BENCHMARK_GROUP: oneAPI
        timeout_in_minutes: 12

      - label: "Metal: Run Benchmarks"
        key: "metal-benchmarks"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
              Pkg.add("Metal");
          '
          julia --project=benchmarks benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/Metalbenchmarks.json"
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "arm64"
        env:
          BENCHMARK_GROUP: Metal
        timeout_in_minutes: 12

      - wait: ~  # Wait for all benchmarks to finish

      - label: "Combine Benchmarks"
        key: "combine-benchmarks"
        depends_on:
          - "cpu-benchmarks"
          - "cuda-benchmarks"
          - "amdgpu-benchmarks"
          - "oneapi-benchmarks"
          - "metal-benchmarks"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          buildkite-agent artifact download "benchmarks/results/*" . --step "*-benchmarks"
          julia --project=benchmarks benchmarks/aggregate.jl
        artifacts:
          - "benchmarks/results/combinedbenchmarks.json"
        agents:
          queue: "benchmark"
        timeout_in_minutes: 15
