steps:
  - group: ":racehorse: Benchmarks"
    steps:
      - label: "CPU: Run Benchmarks (1 thread)"
        key: "cpu-benchmarks-1"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
          '
          julia --project=benchmarks --threads=1 benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/CPUbenchmarks1threads.json"
        agents:
          queue: "benchmark"
        env:
          BENCHMARK_GROUP: CPU
          JULIA_NUM_THREADS: 1
        if: build.message !~ /\[skip benchmarks\]/
        timeout_in_minutes: 12

      - label: "CPU: Run Benchmarks (2 threads)"
        key: "cpu-benchmarks-2"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
          '
          julia --project=benchmarks --threads=2 benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/CPUbenchmarks2threads.json"
        agents:
          queue: "benchmark"
        env:
          BENCHMARK_GROUP: CPU
          JULIA_NUM_THREADS: 2
        if: build.message !~ /\[skip benchmarks\]/
        timeout_in_minutes: 12

      - label: "CPU: Run Benchmarks (4 threads)"
        key: "cpu-benchmarks-4"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
          '
          julia --project=benchmarks --threads=4 benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/CPUbenchmarks4threads.json"
        agents:
          queue: "benchmark"
        env:
          BENCHMARK_GROUP: CPU
          JULIA_NUM_THREADS: 4
        if: build.message !~ /\[skip benchmarks\]/
        timeout_in_minutes: 12

      - label: "CPU: Run Benchmarks (8 threads)"
        key: "cpu-benchmarks-8"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
          '
          julia --project=benchmarks --threads=8 benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/CPUbenchmarks8threads.json"
        agents:
          queue: "benchmark"
        env:
          BENCHMARK_GROUP: CPU
          JULIA_NUM_THREADS: 8
        if: build.message !~ /\[skip benchmarks\]/
        timeout_in_minutes: 12

      - label: "CUDA: Run Benchmarks"
        key: "cuda-benchmarks"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
              Pkg.add("CUDA");
          '
          julia --project=benchmarks benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/CUDAbenchmarks.json"
        agents:
          queue: "juliagpu"
          cuda: "*"
        env:
          BENCHMARK_GROUP: CUDA
        if: build.message !~ /\[skip benchmarks\]/
        timeout_in_minutes: 12

      - label: "AMDGPU: Run Benchmarks"
        key: "amdgpu-benchmarks"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
              Pkg.add("AMDGPU");
          '
          julia --project=benchmarks benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/AMDGPUbenchmarks.json"
        agents:
          queue: "juliagpu"
          rocm: "*"
          rocmgpu: "*"
        env:
          BENCHMARK_GROUP: AMDGPU
        if: build.message !~ /\[skip benchmarks\]/
        timeout_in_minutes: 12

      - label: "oneAPI: Run Benchmarks"
        key: "oneapi-benchmarks"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
              Pkg.add("oneAPI");
          '
          julia --project=benchmarks benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/oneAPIbenchmarks.json"
        agents:
          queue: "juliagpu"
          intel: "*"
        env:
          BENCHMARK_GROUP: oneAPI
        if: build.message !~ /\[skip benchmarks\]/
        timeout_in_minutes: 12

      - label: "Metal: Run Benchmarks"
        key: "metal-benchmarks"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
              using Pkg;
              Pkg.instantiate();
              Pkg.develop(path=pwd());
              Pkg.add("Metal");
          '
          julia --project=benchmarks benchmarks/runbenchmarks.jl
        artifacts:
          - "benchmarks/results/Metalbenchmarks.json"
        agents:
          queue: "juliaecosystem"
          os: "macos"
          arch: "aarch64"
        env:
          BENCHMARK_GROUP: Metal
        if: build.message !~ /\[skip benchmarks\]/
        timeout_in_minutes: 12

      - wait: ~ # Wait for all benchmarks to finish

      - label: "Combine Benchmarks"
        key: "combine-benchmarks"
        depends_on:
          - "cpu-benchmarks-1"
          - "cpu-benchmarks-2"
          - "cpu-benchmarks-4"
          - "cpu-benchmarks-8"
          - "cuda-benchmarks"
          - "oneapi-benchmarks"
          - "amdgpu-benchmarks"
          - "metal-benchmarks"
        plugins:
          - JuliaCI/julia#v1:
              version: "1.10"
        command: |
          julia --project=benchmarks -e '
            using Pkg
            Pkg.instantiate()'
          buildkite-agent artifact download "benchmarks/results/*benchmarks*.json" .
          julia --project=benchmarks benchmarks/aggregate.jl
        artifacts:
          - "benchmarks/results/combinedbenchmarks.json"
        agents:
          queue: "benchmark"
          if: build.message !~ /\[skip benchmarks\]/
          timeout_in_minutes: 15
