project:
  type: website
  output-dir: _site
  execute-dir: project

website:
  title: "Distance Transforms"
  description: "Efficient distance transform operations for CPU and GPU in Julia and Python"
  favicon: "images/favicon.ico"
  
  navbar:
    logo: "https://raw.githubusercontent.com/Dale-Black/DistanceTransforms.jl/master/docs/logo.svg"
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Julia"
        menu:
          - text: "Overview"
            href: julia/index.qmd
          - text: "User Guide"
            href: julia/guide.qmd
          - text: "API Reference"
            href: julia/api.qmd
      - text: "Python"
        menu:
          - text: "Overview"
            href: python/index.qmd
          - text: "User Guide"
            href: python/guide.qmd
          - text: "API Reference"
            href: python/api.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/Dale-Black/DistanceTransforms.jl
        aria-label: GitHub

  sidebar:
    - id: julia
      title: "Julia"
      style: "docked"
      collapse-level: 1
      contents:
        - julia/index.qmd
        - julia/guide.qmd
        - julia/api.qmd
    
    - id: python
      title: "Python"
      style: "docked"
      collapse-level: 1
      contents:
        - python/index.qmd
        - python/guide.qmd
        - python/api.qmd
  
  page-footer:
    left: "Copyright 2024, Dale Black"
    right:
      - icon: github
        href: https://github.com/Dale-Black/DistanceTransforms.jl
      - icon: github
        href: https://github.com/Dale-Black/py-distance-transforms

format:
  html:
    theme: minty
    highlight-style: github
    code-block-bg: true
    code-block-border-left: true
    code-copy: true
    code-link: true
    code-tools: true
    
execute:
  freeze: auto
  enabled: true

# bibliography: references.bib